name: 'Test action'
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

permissions:
    contents: write

jobs:
    tag:
        name: Prova build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install composer deps
              run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress --no-suggest
            - name: Install npm deps
              run: npm ci
            - name: Build files
              run: npm run build
            - name: Build zip
              run: npm run plugin-zip
            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.5
              with:
                type: 'zip'
                filename: 'release.zip'
                exclusions: '*.git* /*node_modules/* .editorconfig'