name: 'Test action'
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

permissions:
    contents: write

jobs:
    tag:
        name: Prova build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Get Composer Cache Directory
              id: get-composer-cache-dir # Instead of composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"
            
            - name: Cache Composer
              uses: actions/cache@v2
              id: composer-cache
              with:
                path: ${{ steps.get-composer-cache-dir.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-composer-
            
            - name: Install composer dependencies
              run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress --no-suggest
            
            - name: Install npm deps
              run: npm ci
            
            - name: Build files
              run: npm run build
        