name: 'Deploy to WordPress.org'
on:
    push:
        tags:
            - '*'
jobs:
    tag:
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Install composer dependencies
              run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress --no-suggest
            
            - name: Install npm deps
              run: npm ci
            
            - name: Build files
              run: npm run build       
              
            - name: Build block manifest
              run: npm run build-blocks-manifest

            - name: WordPress Plugin Deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: 'formello'
