name: 'Deploy to WordPress.org'
on:
    push:
        tags:
            - '*'
jobs:
    tag:
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Get Composer Cache Directory
              id: get-composer-cache-dir
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"
            
            - name: Cache Composer
              uses: actions/cache@v3
              id: composer-cache
              with:
                path: ${{ steps.get-composer-cache-dir.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-composer-
            
            - name: Install composer dependencies
              run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress --no-suggest
            
            - name: Install npm deps
              run: npm ci
            
            - name: Build files
              run: npm run build            

            - name: WordPress Plugin Deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: 'formello'
